@extends('layouts.app')
@section('title','玩法说明与帮助')
@section('content')
<div class="help-page">
  <section class="help-hero"><div><h1>玩法说明与帮助</h1><p>了解棋盘颜色、地标收集、道具、排名和领奖规则</p></div><div><b>{{ $landmarks->whereNotNull('first_unlocked_at')->count() }} / {{ $landmarks->count() }}</b><span>地标收集</span><small>{{ $state->lucky_points }} 点幸运值</small></div><a href="{{ route('game.index') }}">返回棋盘 →</a></section>

  <nav class="help-nav"><a href="#quick">快速上手</a><a href="#legend">棋盘图例</a><a href="#landmarks">地标图鉴</a><a href="#rewards">收集奖励</a><a href="#faq">常见问题</a></nav>

  <section id="quick" class="help-section"><div class="section-heading"><div><span>01</span><h2>五步快速上手</h2></div><form method="post" action="{{ route('help.tutorial') }}">@csrf<button>标记引导已阅读</button></form></div><div class="quick-steps"><article><i>1</i><b>获取机会</b><p>完成签到、任务、充值和邀请。</p></article><article><i>2</i><b>掷骰前进</b><p>每次消耗一次机会，随机前进。</p></article><article><i>3</i><b>触发格子</b><p>落地后自动处理奖励或事件。</p></article><article><i>4</i><b>收集地标</b><p>首次解锁印章，重复转化幸运值。</p></article><article><i>5</i><b>冲击榜单</b><p>按圈数、格子和到达时间排名。</p></article></div></section>

  <section id="legend" class="help-section"><div class="section-heading"><div><span>02</span><h2>棋盘颜色图例</h2></div><p>颜色和类型一一对应</p></div><div class="legend-grid"><article class="safe"><i></i><b>安全格</b><p>无奖励、无惩罚，用于平衡棋盘节奏。</p></article><article class="landmark"><i></i><b>地标格</b><p>解锁旅行印章，重复到达获得幸运值。</p></article><article class="boost"><i></i><b>增益格</b><p>前进、额外机会或其他正向效果。</p></article><article class="risk"><i></i><b>风险格</b><p>炸弹、后退或冰冻等负面事件。</p></article><article class="reward"><i></i><b>奖励格</b><p>现金、VIP、电池或其他奖品。</p></article></div></section>

  <section id="landmarks" class="help-section"><div class="section-heading"><div><span>03</span><h2>地标图鉴</h2></div><p>图鉴在整个活动期间累计，不随圈数重置</p></div><div class="landmark-progress"><div><i style="width:{{ $landmarks->count()?($landmarks->whereNotNull('first_unlocked_at')->count()/$landmarks->count()*100):0 }}%"></i></div><span>已解锁 {{ $landmarks->whereNotNull('first_unlocked_at')->count() }} / {{ $landmarks->count() }}</span><b>幸运值 {{ $state->lucky_points }}</b></div><div class="landmark-grid">@foreach($landmarks as $landmark)<article class="{{ $landmark->first_unlocked_at?'unlocked':'locked' }}"><div><b>{{ $landmark->icon }}</b><span>{{ $landmark->first_unlocked_at?'已解锁':'未解锁' }}</span></div><h3>{{ $landmark->label }}</h3><p>{{ $landmark->description }}</p><small>{{ $landmark->first_unlocked_at?'累计到访 '.$landmark->visit_count.' 次':'落到第 '.($landmark->position+1).' 格解锁' }}</small></article>@endforeach</div></section>

  <section id="rewards" class="help-section"><div class="section-heading"><div><span>04</span><h2>地标收集宝箱</h2></div><p>每个阶段只能领取一次</p></div><div class="landmark-rewards">@foreach($rewards as $reward) @php $ready=$landmarks->whereNotNull('first_unlocked_at')->count()>=$reward->required_count;$isClaimed=in_array($reward->id,$claimed); @endphp<article class="{{ $ready?'ready':'' }}"><b>{{ $isClaimed?'✅':($ready?'🎁':'🔒') }}</b><span>收集 {{ $reward->required_count }} 个</span><h3>{{ $reward->name }}</h3><p>{{ $reward->reward_label }}</p>@if($isClaimed)<em>已领取</em>@elseif($ready)<form method="post" action="{{ route('help.landmarks.claim',$reward->id) }}">@csrf<button>开启宝箱</button></form>@else<small>还差 {{ $reward->required_count-$landmarks->whereNotNull('first_unlocked_at')->count() }} 个地标</small>@endif</article>@endforeach</div></section>

  <section id="faq" class="help-section"><div class="section-heading"><div><span>05</span><h2>常见问题 FAQ</h2></div><p>点击问题展开答案</p></div><div class="faq-layout"><aside>@foreach($faqs as $category=>$entries)<a href="#faq-{{ md5($category) }}">{{ $category }} <span>{{ $entries->count() }}</span></a>@endforeach</aside><div class="faq-content">@foreach($faqs as $category=>$entries)<section id="faq-{{ md5($category) }}"><h3>{{ $category }}</h3>@foreach($entries as $entry)<details><summary>{{ $entry->question }}</summary><p>{{ $entry->answer }}</p></details>@endforeach</section>@endforeach</div></div></section>
</div>
@endsection
