@extends('layouts.app') @section('title','活动管理后台') @section('content')
<div class="admin-page"><div class="page-title"><div><h1>活动运营控制台</h1><p>{{ $activity->name }} · {{ $activity->status }}</p></div><a class="button" href="{{ route('game.index') }}">返回活动</a></div>
<div class="stats">@foreach(['users'=>'参与用户','moves'=>'累计走棋','winners'=>'中奖记录','pending'=>'待处理奖励'] as $key=>$label)<div class="stat-card"><b class="stat-value">{{ $metrics[$key] }}</b><span class="stat-label">{{ $label }}</span></div>@endforeach</div>
<section class="panel"><h2>活动配置</h2><form class="inline-form admin-config" method="post" action="{{ route('admin.activity.update') }}">@csrf<label>开始时间<input type="datetime-local" name="starts_at" value="{{ date('Y-m-d\TH:i',strtotime($activity->starts_at)) }}"></label><label>结束时间<input type="datetime-local" name="ends_at" value="{{ date('Y-m-d\TH:i',strtotime($activity->ends_at)) }}"></label><label>每日充值机会限制<input type="number" name="paid_chance_daily_cap" value="{{ $activity->paid_chance_daily_cap }}"></label><label>状态<select name="status">@foreach(['draft'=>'草稿','active'=>'进行中','frozen'=>'冻结结算','finished'=>'已结束'] as $value=>$label)<option value="{{ $value }}" @selected($activity->status===$value)>{{ $label }}</option>@endforeach</select></label><button class="primary">保存配置</button></form></section>
<section class="panel"><h2>充值与机会调整</h2><div class="admin-two"><form class="inline-form" method="post" action="{{ route('admin.recharge') }}">@csrf<select name="user_id" required><option value="">选择充值用户</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}（{{ $user->email }}）</option>@endforeach</select><input type="number" step="0.01" min="0.01" name="amount" placeholder="充值 USDT" required><button class="primary">确认到账</button></form><form class="inline-form" method="post" action="{{ route('admin.chances.adjust') }}">@csrf<select name="user_id" required><option value="">选择调整用户</option>@foreach($users as $user)<option value="{{ $user->id }}">{{ $user->name }}</option>@endforeach</select><input type="number" name="amount" placeholder="正数补发/负数扣回" required><input name="reason" placeholder="调整原因" required><button>确认调整</button></form></div><p class="muted">正式环境充值应由签名支付回调写入，人工入口用于客服补单。</p></section>
<section class="panel"><h2>任务开关</h2><div class="admin-task-grid">@foreach($tasks as $task)<div><span><b>{{ $task->name }}</b><small>{{ $task->period }} · {{ $task->target }} · 奖励 {{ $task->reward_value }}</small></span><form method="post" action="{{ route('admin.tasks.toggle',$task->id) }}">@csrf<button class="{{ $task->enabled?'':'off' }}">{{ $task->enabled?'已启用':'已停用' }}</button></form></div>@endforeach</div></section>
<section class="panel"><h2>用户进度</h2><div class="table-wrap"><table><thead><tr><th>ID</th><th>用户</th><th>机会</th><th>圈数/格子</th><th>VIP</th><th>电池</th></tr></thead><tbody>@foreach($users as $u)<tr><td>{{ $u->id }}</td><td>{{ $u->name }}<br><small>{{ $u->email }}</small></td><td>{{ $u->chance_balance ?? 0 }}</td><td>{{ $u->completed_laps ?? 0 }} / {{ $u->current_position ?? 0 }}</td><td>{{ $u->vip_level }}</td><td>{{ $u->battery }}</td></tr>@endforeach</tbody></table></div></section>
<section class="panel"><h2>领奖审核</h2><div class="table-wrap"><table><thead><tr><th>用户</th><th>奖品</th><th>资料</th><th>状态</th><th>处理</th></tr></thead><tbody>@forelse($claims as $claim)<tr><td>{{ $claim->name }}</td><td>{{ $claim->prize_name }}</td><td>{{ $claim->claim_data }}</td><td>{{ $claim->status }}</td><td><form class="claim-admin-form" method="post" action="{{ route('admin.claims.update',$claim->id) }}">@csrf<select name="status">@foreach(['submitted','reviewing','processing','issued','rejected'] as $status)<option @selected($claim->status===$status)>{{ $status }}</option>@endforeach</select><input name="admin_note" value="{{ $claim->admin_note }}" placeholder="处理备注"><button>更新</button></form></td></tr>@empty<tr><td colspan="5">暂无领奖申请</td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><h2>中奖发放</h2><div class="table-wrap"><table><thead><tr><th>时间</th><th>用户</th><th>奖品</th><th>状态</th><th>操作</th></tr></thead><tbody>@forelse($winnings as $w)<tr><td>{{ $w->created_at }}</td><td>{{ $w->name }}</td><td>{{ $w->prize_name }}</td><td>{{ $w->status }}</td><td>@if($w->status!=='issued')<form method="post" action="{{ route('admin.winnings.issue',$w->id) }}">@csrf<button>标记已发放</button></form>@else—@endif</td></tr>@empty<tr><td colspan="5">暂无记录</td></tr>@endforelse</tbody></table></div></section>
<section class="panel"><h2>管理员审计日志</h2><div class="table-wrap"><table><thead><tr><th>时间</th><th>管理员</th><th>操作</th><th>对象</th><th>IP</th></tr></thead><tbody>@forelse($audits as $log)<tr><td>{{ $log->created_at }}</td><td>{{ $log->name }}</td><td>{{ $log->action }}</td><td>{{ $log->target_type }} #{{ $log->target_id }}</td><td>{{ $log->ip_address }}</td></tr>@empty<tr><td colspan="5">暂无操作日志</td></tr>@endforelse</tbody></table></div></section></div>
@endsection
