@extends('layouts.app') @section('content')
<div class="dashboard">
 <section class="game-area"><div class="stats"><div><b id="chance">{{ $state->chance_balance }}</b><span>剩余机会</span></div><div><b id="lap">{{ $state->completed_laps }}</b><span>完成圈数</span></div><div><b id="position">{{ $state->current_position }}</b><span>当前格子</span></div><div><b>{{ auth()->user()->vip_level }}</b><span>VIP等级</span></div></div>
 <div class="board" id="board">
 @foreach($cells as $cell) @php if($cell->position<=9){$row=1;$col=$cell->position+1;}elseif($cell->position<=17){$row=$cell->position-8;$col=10;}elseif($cell->position<=27){$row=10;$col=28-$cell->position;}else{$row=37-$cell->position;$col=1;} @endphp
 <div class="cell type-{{ $cell->type }} {{ $state->current_position===$cell->position?'active':'' }}" data-position="{{ $cell->position }}" style="grid-row:{{ $row }};grid-column:{{ $col }};--cell-color:{{ $cell->color }}" title="第{{ $cell->position }}格 {{ $cell->label }}"><i>{{ $cell->icon }}</i><small>{{ $cell->label }}</small>@if($state->current_position===$cell->position)<em class="piece">🚗</em>@endif</div>@endforeach
 <div class="board-center"><div class="event" id="event">{{ $state->is_frozen ? '🧊 已被冰冻，需要一次机会解冻' : '点击骰子开始冒险' }}</div><button id="moveButton" class="dice-btn" data-url="{{ route('game.move') }}"><span id="dice">🎲</span><strong>{{ $state->is_frozen ? '立即解冻' : '立即跳棋' }}</strong></button><p>每次消耗 1 次机会</p></div></div></section>
 <aside class="side-panel"><div class="panel"><h2>今日任务</h2><div class="task"><div><b>连续签到</b><p>普通 5 次，第 7 天 10 次</p></div>@if($checkedIn)<span class="done">已签到</span>@else<form method="post" action="{{ route('game.checkin') }}">@csrf<button>签到</button></form>@endif</div><div class="task"><div><b>本人充值</b><p>每累计 10U 获得 10 次</p></div><span>后台记账</span></div><div class="task"><div><b>邀请好友</b><p>每位有效好友获得 5 次</p></div><button class="copy" data-copy="{{ route('register',['invite'=>auth()->user()->invite_code]) }}">复制链接</button></div><div class="task"><div><b>好友首充达标</b><p>首次满 10U 获得 10 次</p></div><span>{{ $invites }} 人</span></div></div>
 <div class="panel"><h2>实时排行榜 TOP 20</h2><ol class="rank-list">@forelse($leaderboard as $rank=>$item)<li class="{{ $item->user_id===auth()->id()?'me':'' }}"><span>{{ $rank+1 }}. {{ mb_substr($item->name,0,1) }}***</span><b>{{ $item->completed_laps }}圈 {{ $item->current_position }}格</b></li>@empty<li>暂无数据</li>@endforelse</ol></div></aside>
</div>
<section class="records"><details open><summary>机会明细</summary><div class="table-wrap"><table><thead><tr><th>时间</th><th>来源</th><th>变化</th><th>余额</th></tr></thead><tbody>@forelse($transactions as $row)<tr><td>{{ $row->created_at }}</td><td>{{ $row->remark }}</td><td class="{{ $row->amount>0?'plus':'minus' }}">{{ $row->amount>0?'+':'' }}{{ $row->amount }}</td><td>{{ $row->balance_after }}</td></tr>@empty<tr><td colspan="4">暂无记录</td></tr>@endforelse</tbody></table></div></details><details><summary>中奖列表</summary><div class="table-wrap"><table><thead><tr><th>时间</th><th>奖品</th><th>状态</th></tr></thead><tbody>@forelse($winnings as $row)<tr><td>{{ $row->created_at }}</td><td>{{ $row->prize_name }}</td><td>{{ $row->status==='issued'?'已发放':'待发放' }}</td></tr>@empty<tr><td colspan="3">暂无中奖记录</td></tr>@endforelse</tbody></table></div></details></section>
@endsection
@push('scripts')<script>window.gameConfig={position:{{ $state->current_position }},chance:{{ $state->chance_balance }}};</script>@endpush
